setGeneric("psi", function(obj, x) standardGeneric("psi")) 
setGeneric("wt", function(obj, x) standardGeneric("wt")) 
setGeneric("vt", function(obj, x) standardGeneric("vt")) 
setGeneric("erho", function(obj) standardGeneric("erho")) 
setGeneric("erhoLim", function(obj) standardGeneric("erhoLim")) 
setGeneric("erhoLimD", function(obj) standardGeneric("erhoLimD")) 
setGeneric("arpLim", function(obj) standardGeneric("arpLim")) 
setGeneric("csolve", function(obj) standardGeneric("csolve")) 
setGeneric("iterM", function(obj, x, t1, s, eps, maxiter) standardGeneric("iterM")) 
